export const jobsData = [
  {
    logo: '',
    company: 'Photosnap',
    new: true,
    featured: true,
    role: 'Senior Frontend Developer',
    posted: '1d ago',
    work: 'Full Time',
    location: 'USA only',
    tags: ['Frontend', 'Senior', 'HTML', 'CSS', 'JavaScript'],
  },
  {
    logo: '',
    company: 'Manage',
    new: true,
    featured: true,
    role: 'Fullstack Developer',
    posted: '1d ago',
    work: 'Part Time',
    location: 'Remote',
    tags: ['Fullstack', 'Midweight', 'Python', 'React'],
  },
  {
    logo: '',
    company: 'Account',
    new: false,
    featured: false,
    role: 'Junior Frontend Developer',
    posted: '2d ago',
    work: 'Part Time',
    location: 'USA only',
    tags: ['Frontend', 'Junior', 'React', 'Sass', 'JavaScript'],
  },
  {
    logo: '',
    company: 'MyHome',
    new: false,
    featured: false,
    role: 'Junior Frontend Developer',
    posted: '5d ago',
    work: 'Contract',
    location: 'USA only',
    tags: ['Frontend', 'Junior', 'CSS', 'JavaScript'],
  },
  {
    logo: '',
    company: 'Loop Studios',
    new: false,
    featured: false,
    role: 'Software Engineer',
    posted: '1w ago',
    work: 'Full Time',
    location: 'Worldwide',
    tags: ['Fullstack', 'Midweight', 'JavaScript', 'Sass', 'Ruby'],
  },
  {
    logo: '',
    company: 'Facefelt',
    new: false,
    featured: false,
    role: 'Junior Backend Developer',
    posted: '2w ago',
    work: 'Full Time',
    location: 'UK only',
    tags: ['Backend', 'Junior', 'Ruby', 'RoR'],
  },
  {
    logo: '',
    company: 'Shortly',
    new: false,
    featured: false,
    role: 'Junior Developer',
    posted: '2w ago',
    work: 'Full Time',
    location: 'Worldwide',
    tags: ['Frontend', 'Junior', 'HTML', 'Sass', 'Javascript'],
  },
  {
    logo: '',
    company: 'Insure',
    new: false,
    featured: false,
    role: 'Junior Frontend Developer',
    posted: '2w ago',
    work: 'Full Time',
    location: 'USA only',
    tags: ['Frontend', 'Junior', 'HTML', 'Sass', 'Javascript'],
  },
  {
    logo: '',
    company: 'Eyecam Co.',
    new: false,
    featured: false,
    role: 'Fullstack Engineer',
    posted: '3w ago',
    work: 'Full Time',
    location: 'Worldwide',
    tags: ['Fullstack', 'Midweight', 'JavaScript', 'Django', 'Python'],
  },
  {
    logo: '',
    company: 'The Air Filter Company',
    new: false,
    featured: false,
    role: 'Front-end Dev',
    posted: '1m ago',
    work: 'Part Time',
    location: 'Worldwide',
    tags: ['Frontend', 'Junior', 'React', 'Sass', 'Javascript'],
  },
];
